name: Server

on:
  repository_dispatch:
    types: [trigger-server-workflow]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - env:
          SHA: ${{ github.event.client_payload.sha }}
        run: echo $SHA
